### ISSUE TITLE
Bug in product quantizer training

### ISSUE THREAD

**Issue by simonlynen** [ethz-asl/maplab#11]
@dymczykm as discussed last year, the pq training needs to take the residuals (half_descriptor - closest_word) [here](https://github.com/ethz-asl/maplab/blob/master/algorithms/loopclosure/matching-based-loopclosure/src/train-vocabulary.cc#L206)

and not the original half descriptors.

See also [here](https://github.com/ethz-asl/maplab/blob/master/algorithms/loopclosure/inverted-multi-index/include/inverted-multi-index/inverted-multi-product-quantization-index.h#L307)

**Comment by dymczykm** [comment]
@simonlynen thanks for your comment, we will incorporate the fix soon

**Comment by mfehr** [comment]
This has been fixed an is part of the july release candidate.
