### ISSUE TITLE
how find the interface of Binocular vision to maplab？

### ISSUE THREAD

**Issue by Xuleileilei** [ethz-asl/maplab#116]
Where is the interface between binocular vision and Maplab? I want to use SML to make SLAM mapping through maplab.
Please help me ！
THANKS!

**Comment by Xuleileilei** [comment]
I want to use  binocular vision to make SLAM mapping through maplab.

**Comment by Xuleileilei** [comment]
Can I import the video format file directly into maplab?

**Comment by dymczykm** [comment]
Hi @Xuleileilei,
what exactly do you mean by SML and binocular vision? We generally support the visual-inertial sensing modalities, which needs you need both a camera and an IMU sensor to run maplab.

**Comment by Xuleileilei** [comment]
thank you for answering my questions，SML Is the word I misspelled，I am sorry for the meaning of the problem I expressed，now my question has been answered.
