### ISSUE TITLE
Why message_flow instead of ROS topics?

### ISSUE THREAD

**Issue by GoosebumpsFactory** [ethz-asl/maplab#118]
We were curious as to why does maplap define it's own publisher/subscriber based message passing mechanism in `maplap/common/message_flow` instead of using similar functionality available in ROS (i.e., topics)?

**Comment by smauq** [comment]
It was done both for performance reasons to avoid having multiple in-memory copies of the same message as well as to have a guarantee that the messages will be delivered in the exact same order as they were sent also sometimes across different flow topics (see exclusivity groups in the code).

For example ROS nodelets handle the efficiency part of not using multiple copies, but don't have guarantees on the ordering of messages at arrival.

**Comment by mfehr** [comment]
Maybe a small addition to what @smauq said, another reason is simply that in maplab we tried to avoid having any ROS components on the algorithmic level of the system. We use ROS only for visualization and data input, and the latter we tried to keep flexible enough so someone could interface it with another type of data source.

**Comment by GoosebumpsFactory** [comment]
Thanks for that explanation. That makes sense.
