### ISSUE TITLE
How to generate VI-Map by localization-summary-map

### ISSUE THREAD

**Issue by robin1987z** [ethz-asl/maplab#122]
I want to transform some summary map to VI map and merge them.
Is maplab have transformation API can do it? or give me some suggest plz.
Thanks!!

**Comment by dymczykm** [comment]
Thanks for your question, @robin1987z!

Right now, our summary maps contain only limited information (they are summarized and compact) and cannot be used produce a full VI Map again. So this conversion is not possible.

What I would suggest you is to produce normal, full VI-Maps using the estimator and merge them together. Only later, if you need it, you can produce a single summary map out of those merged maps.

**Comment by robin1987z** [comment]
Thanks @dymczykm
