### ISSUE TITLE
Build without ROS

### ISSUE THREAD

**Issue by ahmadhasan2k8** [ethz-asl/maplab#127]
I would really like to use Maplab for the multi-session capabilities and other features it offers. But would really like to avoid using ROS. Is it possible to build and use Maplab without ROS?

**Comment by mfehr** [comment]
Hi @ahmadhasan2k8, it's not possible as it is now. We tried to keep ROS dependencies only in certain packages, like data source and visualization, but there might be some dependencies in other parts as well. It is possible to use catkin without ROS ([source](https://answers.ros.org/question/195636/using-catkin-without-ros/)), but bottom line is, it won't work without some extra effort.
