### ISSUE TITLE
ROS2 support

### ISSUE THREAD

**Issue by GoosebumpsFactory** [ethz-asl/maplab#128]
It looks like ROS is not going to have a May 2019 release. And there will be a final ROS release in May 2020 with python3 support. 

I was wondering what is plan for Maplab and other ETHZ ASL projects in terms of ROS2 and python3 support. The folks in the lab I'm working at are new to ROS but we have adopted ROS as the development platform for our robot given that some of the best robotics research institutions like ETHZ ASL are actively using and developing for ROS. However, we are frustrated by the lack of python3 support and are worried about the transition to ROS2. We were wondering if long time ROS veterans like the people working on Maplab had any advice for newbies like us who are worried about the long term implications of betting on ROS.  Thanks.

**Comment by mfehr** [comment]
Hi @GoosebumpsFactory 

That's a tough question. I doubt there will be a large-scale push in our lab to convert all our tools to ROS2 in the near future. It's more likely that new PhDs will start developing with ROS2 eventually and then convert things they need. I think the only advice, we can give you is to try to follow the following rule: Always try to separate algorithms/logic from the network/ROS interface. We tried to do this in maplab by having ROS specific includes and data types only in visualization and data source packages. This should, at least in theory, allow us or someone else to switch to another communication interface. However, we've all been developing with ROS for so long that I'm sure there are quite a few things (e.g. build system) we would need to adapt or refactor to switch to ROS2 that we didn't think of, or were unaware that they are ROS-specific. Regarding python2/3, maybe someone with more python experience can answer that one :)
