### ISSUE TITLE
HOWTO: Integrate user defined estimator?

### ISSUE THREAD

**Issue by vinodkhare** [ethz-asl/maplab#134]
Hello - how can I integrate a user defined estimator (in place of ROVIOLI) into maplab?

**Comment by mfehr** [comment]
Hi @vinodkhare 
ROVIOLI **is** an example of how to integrate an external estimator into maplab. ROVIO, even though developed at our lab by Michael Bloesch, doesn't have that much in common with maplab and is purely a VIO without map building and localization capabilities. We wrapped it in some maplab building blocks and added those features. Please have a look in the wiki and code to understand how ROVIO was integrated and became ROVIOLI.
