### ISSUE TITLE
Create mesh from TSDF grid issue

### ISSUE THREAD

**Issue by aharmat17** [ethz-asl/maplab#145]
I'm following the instructions at https://github.com/ethz-asl/maplab/wiki/Dense-Reconstruction to create a dense reconstruction. I successfully ran `stereo_dense_reconstruction` to create kRawDepthMap images, and successfully ran `create_tsdf_from_depth_resource` to create a voxblox resource file. However, when I run `create_mesh_from_tsdf_grid`, it fails to load the voxblox resource file, complaining of an empty protobuf message. Here are the commands and the backtrace:

```
maplab <>:/$ load --map_folder="/home/aharmat/data/dock_room_jan31_imgs_backup_tsdf"

Progress: 0:100.0% [#############################################################################]  
--->Complete!

Progress: 0:100.0% [################################] 1:100.0% [################################]   
--->Complete!

I0329 13:59:39.428004 32124 vi-map-serialization.cc:656] Loaded VIMap from "/home/aharmat/data/dock_room_jan31_imgs_backup_tsdf".

maplab <dock_room_jan31_imgs_backup_tsdf>:/$ create_mesh_from_tsdf_grid 

I0329 13:59:41.201735 32124 dense-reconstruction-plugin.cc:99] No mission id list was provided, operating on all missions!

E0329 13:59:53.815192 32124 protobuf_utils.cc:63] Empty protobuf message!

E0329 13:59:53.815390 32124 layer_io.h:63] Could not read block protobuf message number 109087

F0329 13:59:53.887337 32124 resource-loader-inl.h:39] Check failed: loadResourceFromFile(file_path, type, resource) Failed to load voxblox_tsdf_map resource with id d289e109000000000300000000000000 from file: /home/aharmat/data/dock_room_jan31_imgs_backup_tsdf/resources/voxblox_tsdf_map/d289e109000000000300000000000000.tsdf.voxblox

*** Check failure stack trace: ***
*** Aborted at 1553893194 (unix time) try "date -d @1553893194" if you are using GNU date ***
PC: @     0x7f827b8c1428 gsignal
*** SIGABRT (@0x3e900007d7c) received by PID 32124 (TID 0x7f827c9f2ac0) from PID 32124; stack trace: ***
    @     0x7f827b8c14b0 (unknown)
    @     0x7f827b8c1428 gsignal
    @     0x7f827b8c302a abort
    @           0x4029a3 common::glogFailFunctionWithConsoleRecovery()
    @     0x7f827c40526d google::LogMessage::Fail()
    @     0x7f827c407083 google::LogMessage::SendToLog()
    @     0x7f827c404dfb google::LogMessage::Flush()
    @     0x7f827c407a6e google::LogMessageFatal::~LogMessageFatal()
    @     0x7f8252a1888d backend::ResourceLoader::getResource<>()
    @     0x7f8252a18cd7 backend::ResourceMap::getResource<>()
    @     0x7f8252a1244f _ZNSt17_Function_handlerIFivEZN20dense_reconstruction25DenseReconstructionPluginC4EPN6common7ConsoleEPN13visualization21ViwlsGraphRvizPlotterEEUlvE4_E9_M_invokeERKSt9_Any_data
    @     0x7f827c63dcf4 common::CommandRegisterer::processCommand()
    @     0x7f827c641c74 common::Console::RunCommand()
    @     0x7f827c6446c4 common::Console::RunCommandPrompt()
    @           0x4026e1 main
    @     0x7f827b8ac830 __libc_start_main
    @           0x402769 _start
Aborted (core dumped)
```

I don't think the problem is with the TSDF map itself, because if I run `create_tsdf_from_depth_resource` with the `--dense_result_mesh_output_file` option, I get a PLY file with no complaints from the system. The resulting PLY file is very fragmented though, so maybe there is something wrong with the TSDF map after all.... any ideas what's going on?

![image](https://user-images.githubusercontent.com/35509016/55264492-cac08300-5231-11e9-889f-034c47791ac3.png)

My system: 
OS: Ubuntu 16.04
ROS: Kinetic

**Comment by mfehr** [comment]
Hi @aharmat17
Looks like two unrelated issues, I can't say exactly what went wrong while loading the TSDF and exporting it to the mesh. It complains about an empty protobuf message, but based on your screenshot, there is definitely data in there. But as you already pointed out, using the `--dense_result_mesh_output_file` option should give you a mesh as well.

Regarding why your reconstruction looks like it does, that's hard to tell, but common issues are:
 * The voxblox settings are not suitable for the type and resolution of depth information you have. The most important parameters are the voxel size and the truncation distance. The voxel size should roughly correspond to the resolution of your point cloud or be larger (i.e. this means you need to adapt it to both your sensor and your average scene distance), the truncation distance should be at least 2 voxel sizes and reflect how accurate your depth measurements are.
 * The stereo block matcher settings are unsuitable for your cameras. The open cv block matcher we use doesn't really have a perfect set of parameters that suit most cameras, but can have a look at the open cv documentation of it and try to tune them accordingly. (e.g. with tools like this one: https://github.com/guimeira/stereo-tuner)
 * Your sensor calibration might be off, but considering that you managed to get a map based on the same cameras, I think that's not very likely
 * The poses are simply not accurate enough

Try playing with the voxblox parameters and maybe the depth maps directly to see if they make sense.
