### ISSUE TITLE
Build variables remain unchanged

### ISSUE THREAD

**Issue by scharalambous3** [ethz-asl/maplab#146]
Dear maplab team,

 Even though I build maplab at a clean catkin workspace using "catkin build maplab --cmake-args -DROVIO_PATCHSIZE=4 -DROVIO_NMAXFEATURE=250 -DCMAKE_BUILD_TYPE=Release", the selected features remain 25 which is the default value

Using "ccmake ." in the build/rovio folder shows both parameters having the values of 250 and 4 respectively. However, upon running rosrun rovioli (...) the features are still 25 in the frame visualization

This is a screenshot of the frame visualization:
![Rovio (2)](https://user-images.githubusercontent.com/45911515/55761084-6d60d900-5a5e-11e9-8909-a01ad9922c42.png)

I am looking forward to your response about how to resolve this issue: **the build variables do not change the number and size of patches as seen in the frame visualization**

Thanks in advance once again
P.S. I have also posted this in the ROVIO issues, but the issue may be specific to the maplab implementation so I am posting this here as well. 

https://drive.google.com/file/d/1C3DcaupCU35kH_mNZrUryEu9I_7VJ9Jr/view?usp=sharing

**Comment by scharalambous3** [comment]
Update: Rovioli overwrites the build variables of rovio (such as the maximal number of features etc), by static variables. It'd be nice to document this in some way, if possible, for future reference! Thanks

**Comment by mfehr** [comment]
Hi @scharalambous3 
You are right, the reason for this is that we need to be able to set the number of cameras at runtime, which is why we use a factory to provide us with the rovio configuration we need. I added a comment [here](https://github.com/ethz-asl/maplab/wiki/ROVIOLI-Introduction#known-issues).
