### ISSUE TITLE
WHICH MODE OF ROVIOLI IS USED FOR THE 6 DOF POSE ESTIMATE? 

### ISSUE THREAD

**Issue by mechaliomar** [ethz-asl/maplab#150]
In which mode we can get the 6 DOF pose esimate? in VIO or localization mode?

**Comment by mfehr** [comment]
Both, VIO provides T_M_I (6DOF transform from odom frame to inertial/base frame), LOC mode also adds T_G_M (6DOF transform from global/localization frame to odom frame). Please make use of the wiki: https://github.com/ethz-asl/maplab/wiki/ROVIOLI-Introduction
