### ISSUE TITLE
How do I modify the threshold

### ISSUE THREAD

**Issue by wangyuanbiubiubiu** [ethz-asl/maplab#161]
I want to change some thresholds in the file（maplab_ws/src/maplab/algorithms/map-sparsification/src/keyframe-pruning.cc）, such as FLAGS_kf_distance_threshold_m,However, I cannot find the specific configuration file location of this file. I would like to ask, I want to change the default value of this parameter, where should I go to change it?

**Comment by dymczykm** [comment]
The defaults are here:
https://github.com/ethz-asl/maplab/blob/master/algorithms/map-sparsification/src/keyframe-pruning.cc#L13-L19
but you should consider just setting parameters yourself using flags, e.g. when using the maplab console you can write a command:
```
kfh --kf_distance_threshold_m=<your_value> --kf_rotation_threshold_deg=<your_value>
```
and similar for other flags.
