### ISSUE TITLE
Abandoned Packages and Build Fail after 15 installed

### ISSUE THREAD

**Issue by Armand42** [ethz-asl/maplab#164]
**TODO:** ADD YOUR QUESTION/PROBLEM DESCRIPTION HERE
I've been trying to build maplab on my jetson nano but I keep getting build failures around this part of installation:
Errors     << glog_catkin:make /home/armand/catkin_ws/logs/glog_catkin/build.make.000.log
/home/armand/catkin_ws/build/glog_catkin/glog_src-prefix/src/glog_src/missing: Unknown `--is-lightweight' option
Try `/home/armand/catkin_ws/build/glog_catkin/glog_src-prefix/src/glog_src/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
./config.guess: unable to guess system type

This script, last modified 2007-07-22, has failed to recognize
the operating system you are using. It is advised that you
download the most up to date version of the config scripts from

  http://savannah.gnu.org/cgi-bin/viewcvs/*checkout*/config/config/config.guess
and
  http://savannah.gnu.org/cgi-bin/viewcvs/*checkout*/config/config/config.sub

If the version you run (./config.guess) is already up to date, please
send the following data and any information you think might be
pertinent to <config-patches@gnu.org> in order to provide the needed
information to handle your system.

config.guess timestamp = 2007-07-22

uname -m = aarch64
uname -r = 4.9.140-tegra
uname -s = Linux
uname -v = #1 SMP PREEMPT Mon Aug 12 21:16:23 PDT 2019

/usr/bin/uname -p = 
/bin/uname -X     = 

hostinfo               = 
/bin/universe          = 
/usr/bin/arch -k       = 
/bin/arch              = 
/usr/bin/oslevel       = 
/usr/convex/getsysinfo = 

UNAME_MACHINE = aarch64
UNAME_RELEASE = 4.9.140-tegra
UNAME_SYSTEM  = Linux
UNAME_VERSION = #1 SMP PREEMPT Mon Aug 12 21:16:23 PDT 2019
configure: error: cannot guess build type; you must specify one
make[2]: *** [glog_src-prefix/src/glog_src-stamp/glog_src-configure] Error 1
make[1]: *** [CMakeFiles/glog_src.dir/all] Error 2
make: *** [all] Error 2
cd /home/armand/catkin_ws/build/glog_catkin; catkin build --get-env glog_catkin | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
...............................................................................
Failed     << glog_catkin:make                                [ Exited with code 2 ]
Failed    <<< glog_catkin                                     [ 1 minute and 18.1 seconds ]
Abandoned <<< eigen_checks                                    [ Unrelated job failed ]
Abandoned <<< minkindr                                        [ Unrelated job failed ]
Abandoned <<< minkindr_conversions                            [ Unrelated job failed ]
Abandoned <<< agast                                           [ Unrelated job failed ]
Abandoned <<< brisk                                           [ Unrelated job failed ]
Abandoned <<< cv_bridge                                       [ Unrelated job failed ]
Abandoned <<< plotty                                          [ Unrelated job failed ]
Abandoned <<< ceres_catkin                                    [ Unrelated job failed ]
Abandoned <<< voxblox                                         [ Unrelated job failed ]
Abandoned <<< aslam_cv_common                                 [ Unrelated job failed ]
Abandoned <<< aslam_cv_cameras                                [ Unrelated job failed ]
Abandoned <<< aslam_cv_frames                                 [ Unrelated job failed ]
Abandoned <<< aslam_cv_matcher                                [ Unrelated job failed ]
Abandoned <<< aslam_cv_detector                               [ Unrelated job failed ]
Abandoned <<< aslam_cv_geometric_vision                       [ Unrelated job failed ]
Abandoned <<< aslam_cv_pipeline                               [ Unrelated job failed ]
Abandoned <<< aslam_cv_tracker                                [ Unrelated job failed ]
Abandoned <<< aslam_cv_triangulation                          [ Unrelated job failed ]
Abandoned <<< aslam_cv_visualization                          [ Unrelated job failed ]
Abandoned <<< maplab_common                                   [ Unrelated job failed ]
Abandoned <<< aslam_serialization                             [ Unrelated job failed ]
Abandoned <<< console_common                                  [ Unrelated job failed ]
Abandoned <<< map_manager                                     [ Unrelated job failed ]
Abandoned <<< map_resources                                   [ Unrelated job failed ]
Abandoned <<< message_flow                                    [ Unrelated job failed ]
Abandoned <<< posegraph                                       [ Unrelated job failed ]
Abandoned <<< rovio                                           [ Unrelated job failed ]
Abandoned <<< sensors                                         [ Unrelated job failed ]
Abandoned <<< statistics_plugin                               [ Unrelated job failed ]
Abandoned <<< vi_map                                          [ Unrelated job failed ]
Abandoned <<< dense_reconstruction_common                     [ Unrelated job failed ]
Abandoned <<< loopclosure_common                              [ Unrelated job failed ]
Abandoned <<< pose_graph_manipulation_plugin                  [ Unrelated job failed ]
Abandoned <<< simulation                                      [ Unrelated job failed ]
Abandoned <<< geometric_vision_algorithms                     [ Unrelated job failed ]
Abandoned <<< imu_integrator_rk4                              [ Unrelated job failed ]
Abandoned <<< ceres_error_terms                               [ Unrelated job failed ]
Abandoned <<< stereo_dense_reconstruction                     [ Unrelated job failed ]
Abandoned <<< vi_map_helpers                                  [ Unrelated job failed ]
Abandoned <<< map_optimization_legacy                         [ Unrelated job failed ]
Abandoned <<< vi_mapping_test_app                             [ Unrelated job failed ]
Abandoned <<< landmark_triangulation                          [ Unrelated job failed ]
Abandoned <<< vio_common                                      [ Unrelated job failed ]
Abandoned <<< visualization                                   [ Unrelated job failed ]
Abandoned <<< feature_tracking                                [ Unrelated job failed ]
Abandoned <<< landmark_manipulation_plugin                    [ Unrelated job failed ]
Abandoned <<< map_optimization_legacy_plugin                  [ Unrelated job failed ]
Abandoned <<< map_sparsification                              [ Unrelated job failed ]
Abandoned <<< maplab_console                                  [ Unrelated job failed ]
Abandoned <<< online_map_builders                             [ Unrelated job failed ]
Abandoned <<< vi_map_basic_plugin                             [ Unrelated job failed ]
Abandoned <<< vi_map_visualization_plugin                     [ Unrelated job failed ]
Abandoned <<< vocabulary_tree                                 [ Unrelated job failed ]
Abandoned <<< descriptor_projection                           [ Unrelated job failed ]
Abandoned <<< csv_export                                      [ Unrelated job failed ]
Abandoned <<< localization_summary_map                        [ Unrelated job failed ]
Abandoned <<< product_quantization                            [ Unrelated job failed ]
Abandoned <<< inverted_multi_index                            [ Unrelated job failed ]
Abandoned <<< matching_based_loopclosure                      [ Unrelated job failed ]
Abandoned <<< loop_closure_handler                            [ Unrelated job failed ]
Abandoned <<< map_anchoring                                   [ Unrelated job failed ]
Abandoned <<< localization_evaluator                          [ Unrelated job failed ]
Abandoned <<< loop_closure_plugin                             [ Unrelated job failed ]
Abandoned <<< map_anchoring_plugin                            [ Unrelated job failed ]
Abandoned <<< map_optimization                                [ Unrelated job failed ]
Abandoned <<< map_optimization_plugin                         [ Unrelated job failed ]
Abandoned <<< map_sparsification_plugin                       [ Unrelated job failed ]
Abandoned <<< mapping_workflows_plugin                        [ Unrelated job failed ]
Abandoned <<< rovioli                                         [ Unrelated job failed ]
Abandoned <<< vi_map_data_import_export_plugin                [ Unrelated job failed ]
Abandoned <<< vi_map_summarization_plugin                     [ Unrelated job failed ]
Abandoned <<< voxblox_interface                               [ Unrelated job failed ]
Abandoned <<< pmvs_interface                                  [ Unrelated job failed ]
Abandoned <<< dense_reconstruction_plugin                     [ Unrelated job failed ]
_______________________________________________________________________________
Errors     << opencv3_catkin:make /home/armand/catkin_ws/logs/opencv3_catkin/build.make.001.log

And then at the end I'm given this message:

Finished  <<< opengv                                          [ 13 minutes and 16.1 seconds ]
[build] Summary: 15 of 91 packages succeeded.                                  
[build]   Ignored:   15 packages were skipped or are blacklisted.              
[build]   Warnings:  2 packages succeeded with warnings.                       
[build]   Abandoned: 74 packages were abandoned.                               
[build]   Failed:    2 packages failed.                                        
[build] Runtime: 13 minutes and 31.6 seconds total.                            
[build] Note: Workspace packages have changed, please re-source setup files to use them.

I've followed all the installation procedures and still keep running across this problem. How can I fix it? I can provide additional info if needed. Thank you.

---

Before submitting this issue, please consider the following **checklist**:

 - Consult the [FAQ](https://github.com/ethz-asl/maplab/wiki/FAQ) and [Known Issues](https://github.com/ethz-asl/maplab/wiki/Known-Issues) pages.
 - Make sure maplab was installed using the proper [installation instructions](https://github.com/ethz-asl/maplab/wiki/Installation-Ubuntu)
 - For bugs and build problems please add (if applicable):
   - Version of:
     - Operating System (32/64bit, 14.04/16.04/...)
     - Eigen
     - ROS
   - A backtrace (if maplab crashed)
   - Run `catkin config` in your workspace and post it here.
   - Details about the commands/scripts used.
   - Details about special parameter values or manual changes to the system.
   - Pictures/screen recordings
 - For general questions:
   - Please elaborate, we are no mind readers :)

**Comment by dymczykm** [comment]
@Armand42 your error seems to be related to failing compilation of `glog` library, please refer to glog documentation and support to find help.
