### ISSUE TITLE
mapconsole use freak false！

### ISSUE THREAD

**Issue by wangyuanbiubiubiu** [ethz-asl/maplab#165]
When I'm using freak with rovio, I use lc on the map panel and I report an error. Then I delete all my dat files to see if it's because the mapconsole has a brisk configuration file loaded. And I found out that it was. I would like to ask, how can I make my mapconsole also use freak descriptor? This is my configuration file.The picture shows I lack a brisk configuration file, but I actually meant freak

![2019-10-06 10-44-46屏幕截图](https://user-images.githubusercontent.com/42170618/66263505-7b818d80-e826-11e9-9b95-1943bfb38442.png)
![2019-10-06 10-45-20屏幕截图](https://user-images.githubusercontent.com/42170618/66263509-82a89b80-e826-11e9-9700-fa19d2e8172d.png)

**Comment by mfehr** [comment]
Hi @wangyuanbiubiubiu 
Have you tried telling the console which descriptor you want to use with the `--feature_descriptor_type` flag? You can either do that at startup (the setting is persistent for all commands executed later) or when launching the lc command (but then it's not persistent).

**Comment by wangyuanbiubiubiu** [comment]
> Hi @wangyuanbiubiubiu
> Have you tried telling the console which descriptor you want to use with the `--feature_descriptor_type` flag? You can either do that at startup (the setting is persistent for all commands executed later) or when launching the lc command (but then it's not persistent).

I've fixed this problem by adding this command while the terminal is running. But doesn't mapconsole have its own script file? Similar to the rovio script file, so I can add this configuration directly to the file

**Comment by mfehr** [comment]
Glad it worked.
