### ISSUE TITLE
About camera Calibration

### ISSUE THREAD

**Issue by xiaoxiaotao** [ethz-asl/maplab#170]
I use a new camera,MYNTEYE。I have calibrated it.But I can not kow what is the "id"and "label" of "ncamera_calibration.yaml" ,thank you

**Comment by GengMingjin2** [comment]
@xiaoxiaotao Hi, I am using MYNTEYE too. I'd like to ask which toolkit you used to calibrate it. I use kalibr but it hangs. Hope for your reply~

**Comment by xiaoxiaotao** [comment]
@GengMingjin2 https://github.com/slightech/MYNT-EYE-MapLab-Sample.git,It is mynt sample for sample.
