### ISSUE TITLE
Errors  while installing maplab

### ISSUE THREAD

**Issue by ctf11** [ethz-asl/maplab#174]
hi,I am using Ubuntu 18.04 with melodic ROS version.i'm installing maplab ,but  I am facing the following problem :

Errors     << maplab_common:make /home/stf/maplab_ws/logs/maplab_common/build.make.001.log                                                                            
make[2]: /home/stf/maplab_ws/devel/.private/maplab_common/bin/protoc: Command not found
make[2]: /home/stf/maplab_ws/devel/.private/maplab_common/bin/protoc: Command not found
make[2]: *** [compiled_proto/maplab-common/id.pb.cc] Error 127
make[2]: *** 正在等待未完成的任务....
make[2]: *** [compiled_proto/maplab-common/eigen.pb.cc] Error 127
make[1]: *** [CMakeFiles/maplab_common.dir/all] Error 2
make: *** [all] Error 2
Failed     << maplab_common:make                              [ Exited with code 2 ]                                                                                  
Failed    <<< maplab_common                                   [ 2.1 seconds ]

**Comment by jsYangCode** [comment]
@ctf11  hi, friend. i am facing the same problem with you. Have you sloved it, would you please give me some advice about this problem? Thank you a lot!
![Screenshot from 2021-03-25 10-25-17](https://user-images.githubusercontent.com/34529308/112409421-6ec36300-8d54-11eb-83d0-30e013286747.png)
