### ISSUE TITLE
How can i use Candidate March 2018 

### ISSUE THREAD

**Issue by wangyuanbiubiubiu** [ethz-asl/maplab#176]
I wanted to use the code under this branch, but I ran into some problems compiling it. I would like to ask if I need any other operations after checkout?

**Comment by mfehr** [comment]
Hi @wangyuanbiubiubiu 
Please have a look at the PR description  https://github.com/ethz-asl/maplab/pull/55

**Comment by wangyuanbiubiubiu** [comment]
I did follow your steps, but the following error occurred.
![aaa](https://user-images.githubusercontent.com/42170618/68991002-e053ed00-0894-11ea-94c4-d53c578fa026.png)

I thought I would download the package after using your command, but it didn't
![aaaa](https://user-images.githubusercontent.com/42170618/68991023-0aa5aa80-0895-11ea-8951-676570a13b17.png)

**Comment by wangyuanbiubiubiu** [comment]
> Hi @wangyuanbiubiubiu
> Please have a look at the PR description #55

My question is put in the above reply. How can I solve this problem？Thx

**Comment by wangyuanbiubiubiu** [comment]
![ab](https://user-images.githubusercontent.com/42170618/68992964-2b79fa00-08ad-11ea-870e-d09abc1bcccd.png)

**Comment by wangyuanbiubiubiu** [comment]
This is my procedure, can you help me to see what went wrong
step1.git clone https://github.com/ethz-asl/maplab.git --recursive
step2.git checkout pre_release_public/march-2018
step3.git clone https://github.com/ethz-asl/maplab_dependencies --recursive
step4.git checkout pre_release_public/march-2018
step5.git submodule init
step6.git submodule update --recursive
step7.catkin build maplab
