### ISSUE TITLE
How to use resource-importer？

### ISSUE THREAD

**Issue by wangyuanbiubiubiu** [ethz-asl/maplab#178]
I had attached the depth to my vi-map by following the steps on the wiki, but when I ran "create_tsdf_from_depth_resource" I still couldn't recreate it successfully。
![WENTI](https://user-images.githubusercontent.com/42170618/69319917-17eadc80-0c7b-11ea-9e37-552ee9fea0d1.png)
![wenti2](https://user-images.githubusercontent.com/42170618/69319974-3bae2280-0c7b-11ea-9c4a-14f864bf5bd1.png)

**Comment by wangyuanbiubiubiu** [comment]
And I found that if I
Step1: rosrun maplab_console maplab_console
Step2: load --map_folder xx
Step3: SDR balabala
Step4: create_tsdf_from_depth_resource
That's fine.
But when I quit, I can't go back and try to use the depth of the previous binocular calculation, for example
Step1: rosrun maplab_console maplab_console
Step2: load --map_folder xx
Step3: create_tsdf_from_depth_resource
That's not going to work

**Comment by wangyuanbiubiubiu** [comment]
![1937](https://user-images.githubusercontent.com/42170618/69334746-68bbfe80-0c96-11ea-9e4c-b6bedc359546.png)

**Comment by mfehr** [comment]
Hi @wangyuanbiubiubiu 
Did you save the map after running stereo? If you don't then the mp doesn't know it is supposed to have esources when you load it again

**Comment by wangyuanbiubiubiu** [comment]
> Hi @wangyuanbiubiubiu
> Did you save the map after running stereo? If you don't then the mp doesn't know it is supposed to have esources when you load it again

Yes, when I saved it, I did re-execute create_tsdf_from_depth_resource

However, the same problem will still occur when I use my own depth using resource-importer, that is, the reconstruction will not work. Do I need to give the depth map exactly the same timestamp as each node in my map?

**Comment by wangyuanbiubiubiu** [comment]
This is the resources data generated by resource-importer. I noticed that dense_depth_resource_input_type will affect the program. In my case, how much should this parameter be set?
![jietu](https://user-images.githubusercontent.com/42170618/69335782-665aa400-0c98-11ea-87dd-2c2086769d36.png)

**Comment by wangyuanbiubiubiu** [comment]
I set it to 8, and it works

**Comment by wangyuanbiubiubiu** [comment]
yeah，I forget save it，the issue now fix，thx！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Marius Fehr"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月21日(星期四) 晚上7:43
收件人:&nbsp;"ethz-asl/maplab"<maplab@noreply.github.com&gt;;
抄送:&nbsp;"王煜安"<845108949@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ethz-asl/maplab] How to use resource-importer？ (#178)




Hi @wangyuanbiubiubiu
 Did you save the map after running stereo? If you don't then the mp doesn't know it is supposed to have esources when you load it again
