### ISSUE TITLE
Problems with long-running code

### ISSUE THREAD

**Issue by wangyuanbiubiubiu** [ethz-asl/maplab#191]
When I run the rovioli for more than half an hour, my rovioli has been killed. How can I solve this？
![issue](https://user-images.githubusercontent.com/42170618/70843167-d0fe9a00-1e68-11ea-9811-eea17b98f314.png)

**Comment by mfehr** [comment]
ROVIOLI just continues building a map. If you keep running something will eventually use up all your memory or otherwise crash. If you want to fix this then disable map building or write some submapping logic.

**Comment by mfehr** [comment]
Also check the past issues:
https://github.com/ethz-asl/maplab/issues/119
