### ISSUE TITLE
maybe a typo in wiki, about command generate_summary_map_and_save_to_disk

### ISSUE THREAD

**Issue by cxzhp** [ethz-asl/maplab#24]
in this page https://github.com/ethz-asl/maplab/wiki/Preparing-a-single-session-map

at bottom of the article.

1) bad command:

generate_summary_map_and_save_to_disk --summary_map_path path/to/save/localization/summary/map

2) good command:

generate_summary_map_and_save_to_disk --summary_map_save_path path/to/save/localization/summary/map

so, the bad words is "summary_map_path"  -> "summary_map_save_path"

**Comment by mfehr** [comment]
Hi @cxzhp 
Thanks for your report, you are right, the flag was wrong, I just fixed it.
