### ISSUE TITLE
Error when installing Maplab, need help!

### ISSUE THREAD

**Issue by bennywijaya55** [ethz-asl/maplab#247]
Profile:                              default
Extending:          [cached] /opt/ros/kinetic
Workspace:                       /home/benny/Desktop/Maplab
---------------------------------------------------------------
Build Space:        [exists]   /home/benny/Desktop/Maplab/build
Devel Space:        [exists]  /home/benny/Desktop/Maplab/devel
Install Space:      [unused] /home/benny/Desktop/Maplab/install
Log Space:          [exists]   /home/benny/Desktop/Maplab/logs
Source Space:       [exists] /home/benny/Desktop/Maplab/src
DESTDIR:            [unused] None
---------------------------------------------------------------
Devel Space Layout:          merged
Install Space Layout:        None
---------------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
---------------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
---------------------------------------------------------------
Workspace configuration appears valid.
---------------------------------------------------------------
[build] Found '105' packages in 0.0 seconds.                                                                                                                                                               
[build] Package table is up to date.                                                                                                                                                                       
Starting  >>> catkin_simple                                                                                                                                                                                
Starting  >>> doxygen_catkin                                                                                                                                                                               
Starting  >>> kindr                                                                                                                                                                                        
Starting  >>> libnabo                                                                                                                                                                                      
Starting  >>> suitesparse                                                                                                                                                                                  
Finished  <<< doxygen_catkin                                  [ 0.1 seconds ]                                                                                                                              
Finished  <<< suitesparse                                     [ 0.1 seconds ]                                                                                                                              
Finished  <<< catkin_simple                                   [ 0.1 seconds ]                                                                                                                              
Starting  >>> eigen_catkin                                                                                                                                                                                 
Starting  >>> gflags_catkin                                                                                                                                                                                
Starting  >>> hand_eye_calibration                                                                                                                                                                         
Starting  >>> lpsolve_catkin                                                                                                                                                                               
Starting  >>> maplab_test_data                                                                                                                                                                             
Starting  >>> metis_catkin                                                                                                                                                                                 
Starting  >>> opencv3_catkin                                                                                                                                                                               
Starting  >>> protobuf_catkin                                                                                                                                                                              
Starting  >>> yaml_cpp_catkin                                                                                                                                                                              
Finished  <<< kindr                                           [ 0.1 seconds ]                                                                                                                              
Finished  <<< eigen_catkin                                    [ 0.1 seconds ]                                                                                                                              
Starting  >>> opengv                                                                                                                                                                                       
Finished  <<< protobuf_catkin                                 [ 0.1 seconds ]                                                                                                                              
Finished  <<< gflags_catkin                                   [ 0.1 seconds ]                                                                                                                              
Starting  >>> glog_catkin                                                                                                                                                                                  
Finished  <<< maplab_test_data                                [ 0.1 seconds ]                                                                                                                              
Finished  <<< opencv3_catkin                                  [ 0.1 seconds ]                                                                                                                              
Starting  >>> cv_bridge                                                                                                                                                                                    
Finished  <<< hand_eye_calibration                            [ 0.1 seconds ]                                                                                                                              
Starting  >>> end_to_end_common                                                                                                                                                                            
Finished  <<< lpsolve_catkin                                  [ 0.1 seconds ]                                                                                                                              
Finished  <<< yaml_cpp_catkin                                 [ 0.4 seconds ]                                                                                                                              
Finished  <<< metis_catkin                                    [ 0.1 seconds ]                                                                                                                              
Finished  <<< libnabo                                         [ 0.3 seconds ]                                                                                                                              
Finished  <<< glog_catkin                                     [ 0.1 seconds ]                                                                                                                              
Starting  >>> eigen_checks                                                                                                                                                                                 
Starting  >>> agast                                                                                                                                                                                        
Starting  >>> plotty                                                                                                                                                                                       
Starting  >>> ceres_catkin                                                                                                                                                                                 
Finished  <<< end_to_end_common                               [ 0.1 seconds ]                                                                                                                              
Finished  <<< cv_bridge                                       [ 0.2 seconds ]                                                                                                                              
Starting  >>> rovio                                                                                                                                                                                        
Finished  <<< eigen_checks                                    [ 0.1 seconds ]                                                                                                                              
Starting  >>> minkindr                                                                                                                                                                                     
Finished  <<< plotty                                          [ 0.1 seconds ]                                                                                                                              
Finished  <<< opengv                                          [ 0.5 seconds ]                                                                                                                              
Finished  <<< agast                                           [ 0.2 seconds ]                                                                                                                              
Starting  >>> brisk                                                                                                                                                                                        
Finished  <<< ceres_catkin                                    [ 0.1 seconds ]                                                                                                                              
Finished  <<< minkindr                                        [ 0.1 seconds ]                                                                                                                              
Finished  <<< rovio                                           [ 0.3 seconds ]                                                                                                                              
Starting  >>> minkindr_conversions                                                                                                                                                                         
Starting  >>> voxblox                                                                                                                                                                                      
Starting  >>> aslam_cv_common                                                                                                                                                                              
Finished  <<< brisk                                           [ 0.2 seconds ]                                                                                                                              
Finished  <<< minkindr_conversions                            [ 0.1 seconds ]                                                                                                                              
Finished  <<< aslam_cv_common                                 [ 0.1 seconds ]                                                                                                                              
Finished  <<< voxblox                                         [ 0.2 seconds ]                                                                                                                              
Starting  >>> aslam_cv_cameras                                                                                                                                                                             
Starting  >>> maplab_common                                                                                                                                                                                
Finished  <<< aslam_cv_cameras                                [ 0.1 seconds ]                                                                                                                              
Starting  >>> aslam_cv_frames                                                                                                                                                                              
Finished  <<< aslam_cv_frames                                 [ 0.1 seconds ]                                                                                                                              
Starting  >>> aslam_cv_matcher                                                                                                                                                                             
Starting  >>> aslam_cv_pipeline                                                                                                                                                                            
Starting  >>> aslam_cv_triangulation                                                                                                                                                                       
Finished  <<< aslam_cv_triangulation                          [ 0.1 seconds ]                                                                                                                              
Finished  <<< aslam_cv_matcher                                [ 0.1 seconds ]                                                                                                                              
Starting  >>> aslam_cv_detector                                                                                                                                                                            
Starting  >>> aslam_cv_geometric_vision                                                                                                                                                                    
Starting  >>> aslam_cv_visualization                                                                                                                                                                       
Finished  <<< aslam_cv_pipeline                               [ 0.2 seconds ]                                                                                                                              
___________________________________________________________________________________________________________________________________________________________________________________________________________
Errors     << maplab_common:make /home/benny/Desktop/Maplab/logs/maplab_common/build.make.002.log                                                                                                          
/home/benny/Desktop/Maplab/src/maplab/common/maplab-common/src/stringprintf.cc: In function ‘void common::StringAppendV(std::__cxx11::string*, const char*, __va_list_tag*)’:
/home/benny/Desktop/Maplab/src/maplab/common/maplab-common/src/stringprintf.cc:56:14: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (result < sizeof(space)) {
              ^
/usr/bin/ld: cannot find -lreadline
collect2: error: ld returned 1 exit status
make[2]: *** [/home/benny/Desktop/Maplab/devel/lib/libmaplab_common.so] Error 1
make[1]: *** [CMakeFiles/maplab_common.dir/all] Error 2
make: *** [all] Error 2
cd /home/benny/Desktop/Maplab/build/maplab_common; catkin build --get-env maplab_common | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
...........................................................................................................................................................................................................
Failed     << maplab_common:make                              [ Exited with code 2 ]                                                                                                                       
Failed    <<< maplab_common                                   [ 1.1 seconds ]                                                                                                                              
Abandoned <<< aslam_cv_tracker                                [ Unrelated job failed ]                                                                                                                     
Abandoned <<< aslam_serialization                             [ Unrelated job failed ]                                                                                                                     
Abandoned <<< console_common                                  [ Unrelated job failed ]                                                                                                                     
Abandoned <<< map_manager                                     [ Unrelated job failed ]                                                                                                                     
Abandoned <<< map_resources                                   [ Unrelated job failed ]                                                                                                                     
Abandoned <<< message_flow                                    [ Unrelated job failed ]                                                                                                                     
Abandoned <<< posegraph                                       [ Unrelated job failed ]                                                                                                                     
Abandoned <<< sensors                                         [ Unrelated job failed ]                                                                                                                     
Abandoned <<< statistics_plugin                               [ Unrelated job failed ]                                                                                                                     
Abandoned <<< vi_map                                          [ Unrelated job failed ]                                                                                                                     
Abandoned <<< dense_reconstruction_common                     [ Unrelated job failed ]                                                                                                                     
Abandoned <<< loopclosure_common                              [ Unrelated job failed ]                                                                                                                     
Abandoned <<< pose_graph_manipulation_plugin                  [ Unrelated job failed ]                                                                                                                     
Abandoned <<< simulation                                      [ Unrelated job failed ]                                                                                                                     
Abandoned <<< geometric_vision_algorithms                     [ Unrelated job failed ]                                                                                                                     
Abandoned <<< imu_integrator_rk4                              [ Unrelated job failed ]                                                                                                                     
Abandoned <<< ceres_error_terms                               [ Unrelated job failed ]                                                                                                                     
Abandoned <<< stereo_dense_reconstruction                     [ Unrelated job failed ]                                                                                                                     
Abandoned <<< vi_map_helpers                                  [ Unrelated job failed ]                                                                                                                     
Abandoned <<< map_optimization_legacy                         [ Unrelated job failed ]                                                                                                                     
Abandoned <<< vi_mapping_test_app                             [ Unrelated job failed ]                                                                                                                     
Abandoned <<< landmark_triangulation                          [ Unrelated job failed ]                                                                                                                     
Abandoned <<< vio_common                                      [ Unrelated job failed ]                                                                                                                     
Abandoned <<< visualization                                   [ Unrelated job failed ]                                                                                                                     
Abandoned <<< feature_tracking                                [ Unrelated job failed ]                                                                                                                     
Abandoned <<< landmark_manipulation_plugin                    [ Unrelated job failed ]                                                                                                                     
Abandoned <<< map_optimization_legacy_plugin                  [ Unrelated job failed ]                                                                                                                     
Abandoned <<< map_sparsification                              [ Unrelated job failed ]                                                                                                                     
Abandoned <<< maplab_console                                  [ Unrelated job failed ]                                                                                                                     
Abandoned <<< online_map_builders                             [ Unrelated job failed ]                                                                                                                     
Abandoned <<< vi_map_basic_plugin                             [ Unrelated job failed ]                                                                                                                     
Abandoned <<< vi_map_visualization_plugin                     [ Unrelated job failed ]                                                                                                                     
Abandoned <<< vocabulary_tree                                 [ Unrelated job failed ]                                                                                                                     
Abandoned <<< descriptor_projection                           [ Unrelated job failed ]                                                                                                                     
Abandoned <<< csv_export                                      [ Unrelated job failed ]                                                                                                                     
Abandoned <<< localization_summary_map                        [ Unrelated job failed ]                                                                                                                     
Abandoned <<< product_quantization                            [ Unrelated job failed ]                                                                                                                     
Abandoned <<< inverted_multi_index                            [ Unrelated job failed ]                                                                                                                     
Abandoned <<< matching_based_loopclosure                      [ Unrelated job failed ]                                                                                                                     
Abandoned <<< loop_closure_handler                            [ Unrelated job failed ]                                                                                                                     
Abandoned <<< map_anchoring                                   [ Unrelated job failed ]                                                                                                                     
Abandoned <<< localization_evaluator                          [ Unrelated job failed ]                                                                                                                     
Abandoned <<< loop_closure_plugin                             [ Unrelated job failed ]                                                                                                                     
Abandoned <<< map_anchoring_plugin                            [ Unrelated job failed ]                                                                                                                     
Abandoned <<< map_optimization                                [ Unrelated job failed ]                                                                                                                     
Abandoned <<< map_optimization_plugin                         [ Unrelated job failed ]                                                                                                                     
Abandoned <<< map_sparsification_plugin                       [ Unrelated job failed ]                                                                                                                     
Abandoned <<< mapping_workflows_plugin                        [ Unrelated job failed ]                                                                                                                     
Abandoned <<< rovioli                                         [ Unrelated job failed ]                                                                                                                     
Abandoned <<< vi_map_data_import_export_plugin                [ Unrelated job failed ]                                                                                                                     
Abandoned <<< vi_map_summarization_plugin                     [ Unrelated job failed ]                                                                                                                     
Abandoned <<< voxblox_interface                               [ Unrelated job failed ]                                                                                                                     
Abandoned <<< pmvs_interface                                  [ Unrelated job failed ]                                                                                                                     
Abandoned <<< dense_reconstruction_plugin                     [ Unrelated job failed ]                                                                                                                     
___________________________________________________________________________________________________________________________________________________________________________________________________________
Warnings   << aslam_cv_visualization:cmake /home/benny/Desktop/Maplab/logs/aslam_cv_visualization/build.cmake.000.log                                                                                      
Unable to find Doxygen. API Documentation will not be generated
cd /home/benny/Desktop/Maplab/build/aslam_cv_visualization; catkin build --get-env aslam_cv_visualization | catkin env -si  /usr/bin/cmake /home/benny/Desktop/Maplab/src/maplab/aslam_cv2/aslam_cv_visualization --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/benny/Desktop/Maplab/devel -DCMAKE_INSTALL_PREFIX=/home/benny/Desktop/Maplab/install; cd -
...........................................................................................................................................................................................................
___________________________________________________________________________________________________________________________________________________________________________________________________________
Warnings   << aslam_cv_geometric_vision:cmake /home/benny/Desktop/Maplab/logs/aslam_cv_geometric_vision/build.cmake.000.log                                                                                
Unable to find Doxygen. API Documentation will not be generated
cd /home/benny/Desktop/Maplab/build/aslam_cv_geometric_vision; catkin build --get-env aslam_cv_geometric_vision | catkin env -si  /usr/bin/cmake /home/benny/Desktop/Maplab/src/maplab/aslam_cv2/aslam_cv_geometric_vision --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/benny/Desktop/Maplab/devel -DCMAKE_INSTALL_PREFIX=/home/benny/Desktop/Maplab/install; cd -
...........................................................................................................................................................................................................
Finished  <<< aslam_cv_visualization                          [ 4.3 seconds ]                                                                                                                              
Finished  <<< aslam_cv_geometric_vision                       [ 4.8 seconds ]                                                                                                                              
Finished  <<< aslam_cv_detector                               [ 4.9 seconds ]                                                                                                                              
[build] Summary: 36 of 91 packages succeeded.                                                                                                                                                              
[build]   Ignored:   14 packages were skipped or are blacklisted.                                                                                                                                          
[build]   Warnings:  2 packages succeeded with warnings.                                                                                                                                                   
[build]   Abandoned: 54 packages were abandoned.                                                                                                                                                           
[build]   Failed:    1 packages failed.                                                                                                                                                                    
[build] Runtime: 8.8 seconds total.                                                                                                                                                                        
[build] Note: Workspace packages have changed, please re-source setup files to use them.

**Comment by bennywijaya55** [comment]
First, I want to say thank you for this amazing project. I'm having some problems while installing the Maplab. My PC specs is as the following:
- Operating System: Ubuntu 16.04, 64 bit
- ROS: kinetic

**Comment by bennywijaya55** [comment]
This is the log file of build.make.000.log

[  3%] [34m[1mRunning C++ protocol buffer compiler on proto/maplab-common/id.proto[0m
[  6%] [34m[1mRunning C++ protocol buffer compiler on proto/maplab-common/eigen.proto[0m
[35m[1mScanning dependencies of target maplab_common[0m
[  9%] [32mBuilding CXX object CMakeFiles/maplab_common.dir/src/binary-serialization.cc.o[0m
[ 12%] [32mBuilding CXX object CMakeFiles/maplab_common.dir/src/breakpoints.cc.o[0m
[ 16%] [32mBuilding CXX object CMakeFiles/maplab_common.dir/src/combinatorial.cc.o[0m
[ 19%] [32mBuilding CXX object CMakeFiles/maplab_common.dir/src/condition.cc.o[0m
[ 22%] [32mBuilding CXX object CMakeFiles/maplab_common.dir/src/cubic-spline.cc.o[0m
[ 25%] [32mBuilding CXX object CMakeFiles/maplab_common.dir/src/delayed-notification.cc.o[0m
[ 29%] [32mBuilding CXX object CMakeFiles/maplab_common.dir/src/feature-descriptor-ref.cc.o[0m
[ 32%] [32mBuilding CXX object CMakeFiles/maplab_common.dir/src/file-lock.cc.o[0m
[ 35%] [32mBuilding CXX object CMakeFiles/maplab_common.dir/src/file-logger.cc.o[0m
[ 38%] [32mBuilding CXX object CMakeFiles/maplab_common.dir/src/file-system-tools.cc.o[0m
[ 41%] [32mBuilding CXX object CMakeFiles/maplab_common.dir/src/geometry.cc.o[0m
[ 45%] [32mBuilding CXX object CMakeFiles/maplab_common.dir/src/global-coordinate-tools.cc.o[0m
[ 48%] [32mBuilding CXX object CMakeFiles/maplab_common.dir/src/gnuplot-interface.cc.o[0m
[ 51%] [32mBuilding CXX object CMakeFiles/maplab_common.dir/src/gravity-provider.cc.o[0m
[ 54%] [32mBuilding CXX object CMakeFiles/maplab_common.dir/src/histograms.cc.o[0m
[ 58%] [32mBuilding CXX object CMakeFiles/maplab_common.dir/src/multi-threaded-progress-bar.cc.o[0m
[ 61%] [32mBuilding CXX object CMakeFiles/maplab_common.dir/src/progress-bar.cc.o[0m
[ 64%] [32mBuilding CXX object CMakeFiles/maplab_common.dir/src/proto-serialization-helper.cc.o[0m
[ 67%] [32mBuilding CXX object CMakeFiles/maplab_common.dir/src/python-interface.cc.o[0m
[ 70%] [32mBuilding CXX object CMakeFiles/maplab_common.dir/src/shared-gflags.cc.o[0m
[ 74%] [32mBuilding CXX object CMakeFiles/maplab_common.dir/src/sigint-breaker.cc.o[0m
[ 77%] [32mBuilding CXX object CMakeFiles/maplab_common.dir/src/stringprintf.cc.o[0m
[ 80%] [32mBuilding CXX object CMakeFiles/maplab_common.dir/src/test/testing-entrypoint.cc.o[0m
[01m[K/home/benny/Desktop/Maplab/src/maplab/common/maplab-common/src/stringprintf.cc:[m[K In function ‘[01m[Kvoid common::StringAppendV(std::__cxx11::string*, const char*, __va_list_tag*)[m[K’:
[01m[K/home/benny/Desktop/Maplab/src/maplab/common/maplab-common/src/stringprintf.cc:55:14:[m[K [01;35m[Kwarning: [m[Kcomparison between signed and unsigned integer expressions [-Wsign-compare]
   if (result < sizeof(space)) {
[01;32m[K              ^[m[K
[ 83%] [32mBuilding CXX object CMakeFiles/maplab_common.dir/src/threading-helpers.cc.o[0m
[ 87%] [32mBuilding CXX object CMakeFiles/maplab_common.dir/src/tridiagonal-matrix.cc.o[0m
[ 90%] [32mBuilding CXX object CMakeFiles/maplab_common.dir/src/unique-id.cc.o[0m
[ 90%] [34m[1mRunning C++ protocol buffer compiler on proto/maplab-common/eigen.proto[0m
[ 90%] [34m[1mRunning C++ protocol buffer compiler on proto/maplab-common/id.proto[0m
[ 93%] [32mBuilding CXX object CMakeFiles/maplab_common.dir/compiled_proto/maplab-common/eigen.pb.cc.o[0m
[ 96%] [32mBuilding CXX object CMakeFiles/maplab_common.dir/compiled_proto/maplab-common/id.pb.cc.o[0m
[100%] [32m[1mLinking CXX shared library /home/benny/Desktop/Maplab/devel/lib/libmaplab_common.so[0m
/usr/bin/ld: cannot find -lreadline
collect2: error: ld returned 1 exit status
CMakeFiles/maplab_common.dir/build.make:899: recipe for target '/home/benny/Desktop/Maplab/devel/lib/libmaplab_common.so' failed
make[2]: *** [/home/benny/Desktop/Maplab/devel/lib/libmaplab_common.so] Error 1
CMakeFiles/Makefile2:2775: recipe for target 'CMakeFiles/maplab_common.dir/all' failed
make[1]: *** [CMakeFiles/maplab_common.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by mfehr** [comment]
Hi @bennywijaya55 
The readline library is missing. Did you follow the instructions to install the system dependecies? https://github.com/ethz-asl/maplab/wiki/Installation-Ubuntu#install-required-system-packages

**Comment by bennywijaya55** [comment]
thanks! bug solved! 
was missing this step before.. 

sudo apt install autotools-dev ccache doxygen dh-autoreconf git liblapack-dev libblas-dev libgtest-dev libreadline-dev libssh2-1-dev pylint clang-format-3.8 python-autopep8 python-catkin-tools python-pip python-git python-setuptools python-termcolor python-wstool libatlas3-base --yes

sudo pip install requests
