### ISSUE TITLE
Integrating Tracking sensor data with monocular camera for 3D reconstruction

### ISSUE THREAD

**Issue by rakshith95** [ethz-asl/maplab#254]
Hello,
I have a tracking camera which provides the 6DOF pose. While this package has integration with an IMU, I was wondering if it was possible to use the data from this tracking camera for forming 3D mapping along with a monocular camera

**Comment by araujokth** [comment]
Current maplab really requires you to input images and IMU data, so if you do not get IMU data from your camera it wont work out of the box. But you could of course modify maplab to do what you want, like skipping the pose computation with ROVIO and just set the pose directly from your tracking camera, but that will likely require quite a bit of work and good knowledge of the framework
