### ISSUE TITLE
Maplab Works on ROS Lunar + Ubuntu 16?

### ISSUE THREAD

**Issue by kauevestena** [ethz-asl/maplab#27]
And in the future, will support Ubuntu 18.04?

**Comment by mfehr** [comment]
hi @kauevestena 
Currently we don't support ROS Lunar or 18.04, but TBH we haven't tried it yet. It is likely that we will add 18.04 at some point, but at the moment there is nobody working on that. If you are interested in adding support for these versions, we would of course be interested to see your results.

**Comment by ZacharyTaylor** [comment]
I am currently running Ubuntu 17.04 + ROS Lunar and I know maplab compiles though I have not tried running it yet.

**Comment by mfehr** [comment]
Closing this issue now, @kauevestena feel free to open another issue or PR if you end up adding support for this version or have any other questions. Thanks.
