### ISSUE TITLE
"Probably missing in the config file" error

### ISSUE THREAD

**Issue by telemc97** [ethz-asl/maplab#273]
I get the following error when i attemp to run rovioli on CLA rosbag (floor G) using a jetson nano, ubuntu 18.04 and pre_release_public/march-2018 branch

[ INFO] [1598132974.292333560]: Connected to master at [192.168.2.14:1311]
I0823 00:49:35.238173  6553 rovio-factory.cc:178] Loading ROVIO configuration template: /home/tilemahos/test/rovio_default_config.info
**_F0823 00:49:35.525959  6553 PropertyHandler.hpp:105] No such node (Init.Covariance.pmp_0). Probably missing in the config file._**
*** Check failure stack trace: ***
    @       0x7f9fdadb90  google::LogMessage::Fail()
    @       0x7f9fdafac8  google::LogMessage::SendToLog()
    @       0x7f9fdad6c4  google::LogMessage::Flush()
    @       0x7f9fdb034c  google::LogMessageFatal::~LogMessageFatal()
    @       0x7f9fb10d88  LWF::Register<>::readPropertyTree()
    @       0x7f9fb19970  LWF::PropertyHandler::readPropertyTree()
    @       0x7f9fb1e180  LWF::PropertyHandler::readFromPropertyTree()
    @       0x7f9fbf8674  rovio::RovioInterfaceImpl<>::RovioInterfaceImpl()
    @       0x7f9fbf8844  rovio::RovioInterfaceImpl<>::RovioInterfaceImpl()
    @       0x7f9faf6c80  rovioli::constructAndConfigureRovio()
    @       0x7f9fbfcbf4  rovioli::RovioFlow::RovioFlow()
    @       0x7f9fc07854  rovioli::RovioliNode::RovioliNode()
    @       0x5562e14928  (unknown)
    @       0x7f9f6c36e0  __libc_start_main
    @       0x5562e15158  (unknown)
/home/tilemahos/maplab_ws/src/maplab/applications/rovioli/scripts/tutorials/tutorial_euroc: line 20:  6553 Aborted                 (core dumped) rosrun rovioli rovioli --alsologtostderr=1 --v=2 --ncamera_calibration=$NCAMERA_CALIBRATION --imu_parameters_maplab=$IMU_PARAMETERS_MAPLAB --datasource_type="rosbag" --save_map_folder="$LOCALIZATION_MAP_OUTPUT" --optimize_map_to_localization_map=false --map_builder_save_image_as_resources=false --datasource_rosbag=$ROSBAG $REST

**Comment by araujokth** [comment]
Seems like you may be having a problem with your configuration. 

Did you manage to successfully run the tutorials on the euroc dataset https://github.com/ethz-asl/maplab/wiki/Running-ROVIOLI-in-VIO-mode? Did you also modify the calibration files for the CLA dataset http://robotics.ethz.ch/~asl-datasets/maplab/multi_session_mapping_CLA/calibration/?

**Comment by telemc97** [comment]
No, on both datasets (euroc and cla) i used the correct given calibration files but i still get the same exact error (**F0828 12:34:50.698326  9652 PropertyHandler.hpp:105] No such node (Init.Covariance.pmp_0). Probably missing in the config file.**). I have also tried to clean the workspace and rebuild with no luck. I suspect it has something to do with this branch i am using (pre_release_public/march-2018 branch) since i am trying to use maplab on a arm device.

**Comment by araujokth** [comment]
hmm... I am also using that branch (pre_release_public/march-2018) on arm devices (Nano, NX and AGX) and it works fine. I guess you have managed to successfully build without any problems? 

One thing that is a bit strange from your output is that your rovio config template is loading from "/home/tilemahos/test/rovio_default_config.info" when that file should be under applications/rovioli/share. Have you properly sourced the maplab workspace and have you kept the original values in tutorial_euroc?

**Comment by telemc97** [comment]
Yes the build is succesfull with some warnings. As far as for the $ROVIO_CONFIG_DIR variable i change it from its default path to  _/home/tilemahos/test_ by using 
`ROVIO_CONFIG_DIR=/home/tilemahos/test`.
Can that create a problem loading configuration files ?
Also i only change the path of ROVIO_CONFIG_DIR when im using a rosbag. If i'am using rostopics as my data source i use the default path  maplab_ws/src/maplab/applications/rovioli/share and i also get the same error.
maybe i should pay more attention to the warnings i get during build to see if they have to do anything with the error i get ?

**Comment by araujokth** [comment]
Sorry I didnt understand. Why dont you just keep the original value for
that variable when using the rosbags? I mean, if you just follow the
tutorial in the wiki for the rosbag case without changing anything, does it
work or not?

**Comment by telemc97** [comment]
it doesn't. Following the wiki tutorial for the rosbag case i get the same error.

I0829 12:52:55.261324  8330 rovio-factory.cc:178] Loading ROVIO configuration template: /home/tilemahos/maplab_ws/src/maplab/applications/rovioli/share//rovio_default_config.info
**F0829 12:52:55.544064  8330 PropertyHandler.hpp:105] No such node (Init.Covariance.pmp_0). Probably missing in the config file.**
*** Check failure stack trace: ***
    @       0x7fad01eb90  google::LogMessage::Fail()
    @       0x7fad020ac8  google::LogMessage::SendToLog()
    @       0x7fad01e6c4  google::LogMessage::Flush()
    @       0x7fad02134c  google::LogMessageFatal::~LogMessageFatal()
    @       0x7facd81d88  LWF::Register<>::readPropertyTree()
    @       0x7facd8a970  LWF::PropertyHandler::readPropertyTree()
    @       0x7facd8f180  LWF::PropertyHandler::readFromPropertyTree()
    @       0x7face69674  rovio::RovioInterfaceImpl<>::RovioInterfaceImpl()
    @       0x7face69844  rovio::RovioInterfaceImpl<>::RovioInterfaceImpl()
    @       0x7facd67c80  rovioli::constructAndConfigureRovio()
    @       0x7face6dbf4  rovioli::RovioFlow::RovioFlow()
    @       0x7face78854  rovioli::RovioliNode::RovioliNode()
    @       0x557d067928  (unknown)
    @       0x7fac9346e0  __libc_start_main
    @       0x557d068158  (unknown)
/home/tilemahos/maplab_ws/src/maplab/applications/rovioli/scripts/tutorials/tutorial_euroc: line 20:  8330 Aborted                 (core dumped) rosrun rovioli rovioli --alsologtostderr=1 --v=2 --ncamera_calibration=$NCAMERA_CALIBRATION --imu_parameters_maplab=$IMU_PARAMETERS_MAPLAB --datasource_type="rosbag" --save_map_folder="$LOCALIZATION_MAP_OUTPUT" --optimize_map_to_localization_map=false --map_builder_save_image_as_resources=false --datasource_rosbag=$ROSBAG $REST

**Comment by araujokth** [comment]
hmm strange.

Which branch of maplab_dependencies are you using? You should also use the pre-release-march-2018 branch https://github.com/ethz-asl/maplab_dependencies/tree/pre_release_public/march-2018 

When you built, did you have to do any modifications to openc3_catkin inside maplab_dependencies? for me I had to do these steps: https://github.com/ethz-asl/maplab/issues/155#issuecomment-681046278

Could you create a new workspace, and follow again the installation instructions for maplab and maplab_dependencies using the pre-release-march-2018 branch and applying the modifications I mention above, and try to run the tutorial_euroc example again?

**Comment by araujokth** [comment]
Another thing, could you check that your rovio_default_config.info has the values pmp_0 defined like here https://github.com/ethz-asl/maplab/blob/pre_release_public/march-2018/applications/rovioli/share/rovio_default_config.info#L55

**Comment by telemc97** [comment]
Thank you very much !! my rovio_default_config.info was missing the pmp_0 values as it was taken from the master branch
