### ISSUE TITLE
ROVIOLI in VIO mode runs very slow

### ISSUE THREAD

**Issue by sumitsarkar1** [ethz-asl/maplab#321]
I have successfully installed master branch of maplab, but the ROVIOLI in VIO example runs very slow with MH_01_easy.bag. I checked the Hz of rosbag topics which are fine with imu at 200 Hz and cams at 20 Hz. However the tutorial example runs very slow as I see in the "Tracker0" window the images are updated once or twice in 2 seconds and I get timeout and other warnings. Please help. I have strictly followed most of the installation and tutorial guidelines.

![Screenshot from 2021-07-01 06-32-34](https://user-images.githubusercontent.com/4591743/124050640-92273980-da38-11eb-9537-5f7f9a3cd414.png)
![Screenshot from 2021-07-01 06-32-55](https://user-images.githubusercontent.com/4591743/124050706-b2ef8f00-da38-11eb-8ef1-8be03fd41e7d.png)
![Screenshot from 2021-07-01 06-33-01](https://user-images.githubusercontent.com/4591743/124050712-b5ea7f80-da38-11eb-8e40-a5cd97c5d3d5.png)

**Comment by smauq** [comment]
Can you say exactly how you launch everything? And just a few details about your setup, like are you trying to run it through ssh, in a docker etc?

**Comment by sumitsarkar1** [comment]
1.) Platform : i7 , 8GB RAM, Ubuntu 16 , ROS Kinetic
2.) No ssh , no docker, just a laptop
3.) Then I follow the instructions at https://github.com/ethz-asl/maplab/wiki/Running-ROVIOLI-in-VIO-mode

**Comment by smauq** [comment]
Can I suggest two things to see if any help. Instead of master branch take the newest release candidate, i.e. this https://github.com/ethz-asl/maplab/tree/pre_release_public/july-2018 and try again. And also while running ROVIOLI can you take a screenshot of htop to see the CPU usage?

**Comment by sumitsarkar1** [comment]
It got solved with the master branch...I was tampering with the launch file...my bad..thanx a lot for the response
