### ISSUE TITLE
map-structure/sensors/src/sensor-extrinsics.cc is missing #include <random>

### ISSUE THREAD

**Issue by pumaking** [ethz-asl/maplab#34]
std::default_random_engine is used which requires the <random> std header.

gcc --version
  gcc (Ubuntu 7.2.0-1ubuntu1~16.04) 7.2.0

**Comment by mfehr** [comment]
Thanks for the report. I'm assuming you're compiling maplab on something other than Ubuntu 14.04/16.04  (OSX?) This PR (#33) adapts maplab for a OSX setup and fixes this issue. If you discover further fixes to compile maplab on your particular platform, we would certainly be interested in a pull request with some info on your setup.
