### ISSUE TITLE
No valid coordinate data!???

### ISSUE THREAD

**Issue by Pan-long-ming** [ethz-asl/maplab#346]
When i run rovioli using my own image data,it occurs error-"    ERROR: No valid coordinate data!",Why this could happen,what it means?

**Comment by smauq** [comment]
No idea, haven't seen this before. The error comes deep from within rovio. I would first double-check everything (calibration, topics, etc.). Then maybe you have something specific and weird, like an extremely tiny resolution image might not work?

**Comment by Pan-long-ming** [comment]
Thank you, I know that is the rovio's problem.

**Comment by ShrutheeshIR** [comment]
Hi @Pan-long-ming , I face the same issue with the TUM VI dataset, were you able to fix it?

**Comment by B1ueber2y** [comment]
Helloo, facing the same issue. Were you able to fix it? @Pan-long-ming @ShrutheeshIR
