### ISSUE TITLE
map-manager-inl.h: return-statement with no value in function returning bool

### ISSUE THREAD

**Issue by pumaking** [ethz-asl/maplab#35]
https://github.com/ethz-asl/maplab/blob/94c1561a1c95ce3f0ee88557afa5353dbcaa8a62/backend/map-manager/include/map-manager/map-manager-inl.h#L491

This should say return false, I'm assuming.

**Comment by mfehr** [comment]
Thanks for your report. You are obviously right, this is gonna be fixed in this PR: #33
