### ISSUE TITLE
Source of code in for algorithms/imu-integrator-rk4?

### ISSUE THREAD

**Issue by cfneuhaus** [ethz-asl/maplab#43]
Hi,

I am wondering if there is any publication that the code in
algorithms/imu-integrator-rk4
is based on? It looks very similar to 

Leutenegger, S., Lynen, S., Bosse, M., Siegwart, R., & Furgale, P. (2015). Keyframe-based visual–inertial odometry using nonlinear optimization. The International Journal of Robotics Research, 34(3), 314-334.

However it is not quite the same (for example the paper has a bounded random walk for the accelerometer bias, which the code doesn't have). Which publication should be cited when using the mentioned code?

I already checked the list of publications and did not find it there.

Thanks

**Comment by dymczykm** [comment]
Hi,
sorry for a late response. Both the conventions as well as the math are similar to the paper of Joel Hoesch et al., Consistency Analysis and Improvement of Vision-aided Inertial Navigation, 2014.
https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=6605544&tag=1
See especially the discrete time formulation around the equation (22).

**Comment by cfneuhaus** [comment]
Thank you :-)
