### ISSUE TITLE
rovioli node can not run on the ubuntu without the desktop environment

### ISSUE THREAD

**Issue by BryceeeeeChen** [ethz-asl/maplab#47]
Hi, I'm trying to rosrun rovioli on an Ubuntu server platform and use another computer to operate it. But the node will die after "cannot open display" error. I did not experience this kind of issue when I used the desktop version Ubuntu. And I have tried set MAKE_SCENE and DMAKE_SCENE to 0 in the maplab_dependencies/internal/maplab_rovio/CMakeLists.txt, which doesn't solve this problem. Could anyone help me with this? Thanks! 
![screenshot from 2018-03-01 10-23-07](https://user-images.githubusercontent.com/16990429/36825542-1d3b55c6-1d43-11e8-8fe1-cc76ff04090e.png)

**Comment by eggerk** [comment]
Hi @BryceeeeeChen,

you can set the flag `--rovio_enable_frame_visualization=false` when running rovioli to disable the graphical output.

**Comment by BryceeeeeChen** [comment]
Thank you @eggerk ! Problem solved.
