### ISSUE TITLE
Camera IMU Sync Rovioli

### ISSUE THREAD

**Issue by goldbattle** [ethz-asl/maplab#6]
I don't see a location where the system is handling a camera-imu time offset generated for kalibr. Is there an ideal location to add this? My thought is to simply subtract from the incoming ROS timestamp, but it could be incorporated into the `imu-camera-synchronizer.cc`, which one would be ideal?

Based on the warnings I get (camera/imu data out-of-order) I need to also look into if this impacts the syncing (I don't think it should from a quick glance).

**Comment by mfehr** [comment]
@goldbattle the `imu-camera-synchronizer` is only used by the maplab components (localization and map building) of ROVIOLI, but not in ROVIO. ROVIO takes the raw sensor measurements. IMO adding this offset as early as possible in the flow would be preferred, i.e. in the data source logic (datasource-rosbag and datasource-rostopic) or one level above (once for ROVIO and once for the imu-cam sync which is needed for maplab). 

![schne4_rovioli-flow](https://user-images.githubusercontent.com/5071588/34889315-d7cf5a22-f7cd-11e7-818a-5d324b714448.PNG)
