### ISSUE TITLE
Is this a mistake? In common/vio-common/imu-measurements-buffer.h

### ISSUE THREAD

**Issue by democheng** [ethz-asl/maplab#61]
I find sth wrong(?) in line 107 to line 109
  typedef std::pair<int64_t, **vio::ImuData**> BufferElement;
  typedef Eigen::aligned_allocator<BufferElement> BufferAllocator;
  typedef common::TemporalBuffer<**vio::ImuMeasurement**, BufferAllocator> Buffer;

**vio::ImuData** and **vio::ImuMeasurement** is different, and **vio::ImuData** is a data member of **vio::ImuMeasurement**, in xcode 9 it is unhappy and throws a error _static_assert failed "Allocator::value_type must be same type as value_type"_

Is this a mistake?

**Comment by schneith** [comment]
That looks like a bug. Thanks for reporting.
