### ISSUE TITLE
Nobody notices the memory leak in vi-map-optimizer.cc ?

### ISSUE THREAD

**Issue by NewThinker-Jiwey** [ethz-asl/maplab#89]
The variable [optimization_problem](https://github.com/ethz-asl/maplab/blob/2db80eb0c1d56e4077edffcf43bbce02deb8a046/algorithms/map-optimization/src/vi-map-optimizer.cc#L57) is allocated in ```VIMapOptimizer::optimizeVisualInertial()```, but not been freed anywhere.
Is it necessary to create a pull request for this ?

**Comment by dymczykm** [comment]
@NewThinker-Jiwey You're right, #90 should fix that

**Comment by NewThinker-Jiwey** [comment]
@dymczykm  Nice work !

But I might not have reported that bug completely. A similar mistake is still in the ```vi-map-relaxation``` part, see [here](https://github.com/ethz-asl/maplab/blob/2db80eb0c1d56e4077edffcf43bbce02deb8a046/algorithms/map-optimization/src/vi-map-relaxation.cc#L116)
