### ISSUE TITLE
Clarify ROVIOLI config in beginners tutorial

### ISSUE THREAD

**Issue by hermannsblum** [ethz-asl/maplab#91]
As a Newbie to ROS and maplab, I followed your tutorial and it took me now quite a while to figure out how the calibration and config files have to be set up. To clarify the wiki in this regard, I'd propose the following changes: (Unfortunately, PRs to the wiki are not possible, therefore this issue).

on this page: https://github.com/ethz-asl/maplab/wiki/Sensor-Calibration-Format
```
[ROVIOLI](Running-ROVIOLI-in-VIO-mode) uses three different calibration files:
- `ncamera_calibration`
- `imu_parameters_maplab`
- `imu_parameters_rovio`

Additionally, the standard config file [`rovio_default_config.info`](https://github.com/ethz-asl/maplab/blob/master/applications/rovioli/share/rovio_default_config.info) is required to sit in the same directory as the calibration files.
```

on this page: https://github.com/ethz-asl/maplab/wiki/Running-ROVIOLI-in-VIO-mode
```
# Requirements
To run a ROVIOLI, the following calibration files are required:
- Camera calibration, [example file for the Euroc datasets](https://github.com/ethz-asl/maplab/blob/master/applications/rovioli/share/ncamera-euroc.yaml)
- IMU parameters maplab, [example file for the Euroc datasets](https://github.com/ethz-asl/maplab/blob/master/applications/rovioli/share/imu-adis16488.yaml)
- IMU parameters Rovio, [example file for the Euroc datasets](https://github.com/ethz-asl/maplab/blob/master/applications/rovioli/share/imu-sigmas-rovio.yaml)

Place the calibration files into the ROVIOLI config directory 'src/maplab/applications/rovioli/share`.

See [[Sensor Calibration Format]] for more information on these files.
```

The basic problem is that there is no documentation on `rovio_default_config.info` and the tutorials do not introduce the environment variable `$ROVIO_CONFIG_DIR`, which at first hand looks simply like the path to the calibration files. However, if you set `$ROVIO_CONFIG_DIR` to the location of the calibration files and you do not have a proper `rovio_default_config.info` in the same directory, you actually run into issue #16 as rovioli will work, but super slowly.

**Comment by dymczykm** [comment]
@hermannsblum thanks for your report, I have updated the two wiki articles with pretty much what you suggested. I hope it will be easier to understand now.

Thanks once again for your help!
