### ISSUE TITLE
Error while installing maplab_common?

### ISSUE THREAD

**Issue by Keudeugi** [ethz-asl/maplab#93]
Hi, first of thanks for providing this awesome program!

I'm currently getting problems while installing maplab, and it seems related with installation of module: maplab_common.

Specs: Ubuntu 16.04, ROS Kinetic, Catkin workspace (User spec: I started working with Ubuntu from three days ago; Newbie)

In the installation step, though I already installed ROS kinetic & catkin, I followed all of the commands provided in the page.
Everything seemed as work except one command; **catkin build maplab**
A bunch of packages failed to be installed, following issue shows similar result about the error: [https://github.com/ethz-asl/maplab/issues/92](url)

As I examined build log, there was an error seemed related with Cmake: CMake Error at /home/piljoong/maplab_ws/devel/share/catkin_simple/cmake/catkin_simple-extras.cmake:38 (find_package)
After this error I met list of failed packages:
![image](https://user-images.githubusercontent.com/9735077/45262537-726f9280-b453-11e8-955d-80e9850e3d56.png)

Did I miss a step while installing the project? Can I provide an additional informations for figuring this out? Thanks in advance.

PS. Here's my catkin config:
![image](https://user-images.githubusercontent.com/9735077/45262411-e9eff280-b450-11e8-9dca-f478b141bd78.png)

**Comment by mfehr** [comment]
Hi @Keudeugi ,
Can you check if aslam_cv2 (and the package aslam_cv_common) is actually there? It's a submodule of maplab and if you forgot to use the `--recursive` flag when cloning the repo or didn't call `git submodule init` / `git submodule update` at some point it might not be there.

**Comment by Keudeugi** [comment]
Oh my, what a shame. Maybe I cloned submodules only for maplab_dependencies. Thank you!

**Comment by karankatiyar92** [comment]
> Hi @Keudeugi ,
> Can you check if aslam_cv2 (and the package aslam_cv_common) is actually there? It's a submodule of maplab and if you forgot to use the `--recursive` flag when cloning the repo or didn't call `git submodule init` / `git submodule update` at some point it might not be there.

i have those both still i get the same issue ?, any suggestions how can i fix it
