### ISSUE TITLE
Where to find list of flags for  script?

### ISSUE THREAD

**Issue by rhklite** [ethz-asl/maplab#97]
Where might i find a complete list of flags and explanation of their uses for this script?
`rosrun rovioli run_rovioli_live`

**Comment by smauq** [comment]
`rosrun rovioli rovioli --help` will show you all the flags and their explanations. You can then grep for relevant keywords, e.g. `rosrun rovioli rovioli --help | grep save -B 2 -A 2`, will search for the word "save" and show two lines after and before where the word appeared.
